{% set version = '0.1.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-shinytitle
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/shinytitle_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/shinytitle/shinytitle_{{ version }}.tar.gz
  sha256: 5d2f9d4f5a8918c34a27f1bc1d71d351035bf7ee97f5896d6ee36f5c9dd005cc

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-shiny
  run:
    - r-base
    - r-shiny

test:
  commands:
    - $R -e "library('shinytitle')"           # [not win]
    - "\"%R%\" -e \"library('shinytitle')\""  # [win]

about:
  home: https://github.com/ashbaldry/shinytitle, https://ashbaldry.github.io/shinytitle/
  license: GPL-2.0-or-later
  summary: Enables the ability to change or flash the title of the browser window during a 'shiny'
    session.
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: shinytitle
# Type: Package
# Title: Update Browser Window Title in 'shiny' Session
# Version: 0.1.0
# Authors@R: person("Ashley", "Baldry", email = "arbaldry91@gmail.com", role = c("aut", "cre"))
# Description: Enables the ability to change or flash the title of the browser window during a 'shiny' session.
# URL: https://github.com/ashbaldry/shinytitle, https://ashbaldry.github.io/shinytitle/
# BugReports: https://github.com/ashbaldry/shinytitle/issues
# Imports: shiny
# Suggests: testthat (>= 3.0.0)
# License: GPL-2
# Encoding: UTF-8
# RoxygenNote: 7.1.1
# NeedsCompilation: no
# Packaged: 2021-06-15 17:58:52 UTC; arbal
# Author: Ashley Baldry [aut, cre]
# Maintainer: Ashley Baldry <arbaldry91@gmail.com>
# Repository: CRAN
# Date/Publication: 2021-06-16 10:40:02 UTC
